version: '3.8'

services:
  django:
    build: ./django
    command: "gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3.11-management-alpine"
    ports:
      - "5672:5672"    # RabbitMQ broker
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"

  celery:
    build: ./django
    command: "celery -A config worker --loglevel=info"
    volumes:
      - ./django:/app
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
